package model.eo.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 10 00:22:54 BST 2018
// ---------------------------------------------------------------------
public interface AppModule
  extends ApplicationModule
{
  boolean createNewDeptFromAM();
}

