package model.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 09 23:04:08 BST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsImpl
  extends EntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    DepartmentId,
    DepartmentName,
    ManagerId,
    LocationId,
    Employees;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
  public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
  public static final int MANAGERID = AttributesEnum.ManagerId.index();
  public static final int LOCATIONID = AttributesEnum.LocationId.index();
  public static final int EMPLOYEES = AttributesEnum.Employees.index();

  /**
   * This is the default constructor (do not remove).
   */
  public DepartmentsImpl()
  {
  }

  /**
   * Gets the attribute value for DepartmentId, using the alias name DepartmentId.
   * @return the value of DepartmentId
   */
  public Integer getDepartmentId()
  {
    return (Integer) getAttributeInternal(DEPARTMENTID);
  }

  /**
   * Sets <code>value</code> as the attribute value for DepartmentId.
   * @param value value to set the DepartmentId
   */
  public void setDepartmentId(Integer value)
  {
    setAttributeInternal(DEPARTMENTID, value);
  }

  /**
   * Gets the attribute value for DepartmentName, using the alias name DepartmentName.
   * @return the value of DepartmentName
   */
  public String getDepartmentName()
  {
    return (String) getAttributeInternal(DEPARTMENTNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for DepartmentName.
   * @param value value to set the DepartmentName
   */
  public void setDepartmentName(String value)
  {
    setAttributeInternal(DEPARTMENTNAME, value);
    System.out.println("New dept name value: " + value);
    setManagerId(100);
  }

  /**
   * Gets the attribute value for ManagerId, using the alias name ManagerId.
   * @return the value of ManagerId
   */
  public Integer getManagerId()
  {
    return (Integer) getAttributeInternal(MANAGERID);
  }

  /**
   * Sets <code>value</code> as the attribute value for ManagerId.
   * @param value value to set the ManagerId
   */
  public void setManagerId(Integer value)
  {
    setAttributeInternal(MANAGERID, value);
  }

  /**
   * Gets the attribute value for LocationId, using the alias name LocationId.
   * @return the value of LocationId
   */
  public Integer getLocationId()
  {
    return (Integer) getAttributeInternal(LOCATIONID);
  }

  /**
   * Sets <code>value</code> as the attribute value for LocationId.
   * @param value value to set the LocationId
   */
  public void setLocationId(Integer value)
  {
    setAttributeInternal(LOCATIONID, value);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getEmployees()
  {
    return (RowIterator) getAttributeInternal(EMPLOYEES);
  }

  /**
   * @param departmentId key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(Integer departmentId)
  {
    return new Key(new Object[] { departmentId });
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("model.eo.Departments");
  }

  /**
   * Add attribute defaulting logic in this method.
   * @param attributeList list of attribute names/values to initialize the row
   */
  protected void create(AttributeList attributeList)
  {
    // before row is created
    super.create(attributeList);
    
    setDepartmentName("My Dept");
    setManagerId(100);
  }

  /**
   * Add entity remove logic in this method.
   */
  public void remove()
  {
    // check if it has a detail rows
    super.remove();
    
  }

  /**
   * Add locking logic here.
   */
  public void lock()
  {
    super.lock();
  }

  /**
   * Custom DML update/insert/delete logic here.
   * @param operation the operation type
   * @param e the transaction event
   */
  protected void doDML(int operation, TransactionEvent e)
  {
    if(operation == DML_INSERT)
    {
      System.out.println("I am in pre insert in DML: " + getDepartmentId());
    }
    
    if(operation == DML_UPDATE)
    {
      System.out.println("I am in pre update in DML: " + getDepartmentId());
    }
    
    if(operation == DML_DELETE)
    {
      System.out.println("I am in pre delete in DML: " + getDepartmentId());
    }
    
    super.doDML(operation, e);
    
    if(operation == DML_INSERT)
    {
      System.out.println("I am in post insert in DML: " + getDepartmentId());
    }
    
    if(operation == DML_UPDATE)
    {
      System.out.println("I am in post update in DML: " + getDepartmentId());
    }
    
    if(operation == DML_DELETE)
    {
      System.out.println("I am in post delete in DML: " + getDepartmentId());
    }
    
  }
}

