--------------------------------------------------------
--  File created - Saturday-September-22-2018   
--------------------------------------------------------
REM INSERTING into SCHOOL.TEACHER_CLASSES
SET DEFINE OFF;
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (2,3);
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (2,4);
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (1,1);
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (1,2);
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (4,5);
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (5,8);
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (5,5);
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (4,8);
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (2,9);
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (1,5);
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (5,1);
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (4,1);
Insert into SCHOOL.TEACHER_CLASSES (TEACHER_FK,CLASSROOM_FK) values (2,1);
