package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 10 00:07:27 BST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public DepartmentsViewImpl()
  {
  }


  /*@Override
  protected void executeQueryForCollection(Object object, Object[] object2, int i)
  {
    this.setWhereClause("DEPARTMENT_ID >= 50");
    super.executeQueryForCollection(object, object2, i);
  }*/
}

