package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 28 01:42:03 BST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StaticViewImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public StaticViewImpl()
  {
  }
}

